#!/bin/bash

PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin
export PATH

# Exit when no parted was found
which parted || exit 1

[ -f /.stretchfs ] || exit 1

partinfo=` parted -s -m /dev/mmcblk0 unit B print | tail -n1 `
partnum=` echo $partinfo | awk -F ':' '{print $1}' `
partstart=` echo $partinfo | awk -F ':' '{print $2}' `
[ -z "$partnum" ] && exit 1
[ -z "$partstart" ] && exit 1

# Stretch partition and reboot
if [ -f /.stretchpart ] ; then
	parted -s -m /dev/mmcblk0 unit B resizepart "$partnum" '100%'
	sync
	sleep 1
	reboot
	exit 0
fi

# Online resize and reboot
resize2fs /dev/mmcblk0p${partnum}
rm -f /.stretchfs
sync
reboot
exit 0
